package enums;

public enum FornecedorEnums {
    JA_CADASTRADO,
    NAO_CADASTRADO,
    ERRO_GENERICO,
    SUCESSO_CADASTRAR,
    SUCESSO_APAGAR,
    VERIFICA_EXISTE,
    CONSULTA,
    SUCESSO_CONSULTA
}
